# Generated by Django 2.1.3 on 2019-08-28 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cn_vson', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CN_portfolio',
            new_name='Portfolio',
        ),
    ]
