# Generated by Django 2.1.3 on 2019-08-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn_vson', '0002_auto_20190828_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_category', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=2000)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='category',
            new_name='portfolio_category',
        ),
    ]
