# Generated by Django 2.1.3 on 2019-08-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn_vson', '0005_bio_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio_img',
            name='bio_img',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
