# Generated by Django 2.1.3 on 2019-08-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn_vson', '0006_auto_20190830_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio_img',
            name='bio_img',
            field=models.ImageField(upload_to='cn_vson/static/images/'),
        ),
    ]
