# Generated by Django 2.1.3 on 2019-08-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn_vson', '0007_auto_20190830_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio_img',
            name='bio_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
