# Generated by Django 2.1.3 on 2019-08-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn_vson', '0008_auto_20190831_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio_img',
            name='bio_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
