# Generated by Django 2.1.3 on 2019-08-28 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CN_portfolio',
        ),
    ]
